apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kvcache-api-layer.fullname" . }}-config
  labels:
    {{- include "kvcache-api-layer.labels" . | nindent 4 }}
  {{- with include "kvcache-api-layer.annotations" . }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
data:
  config.yaml: |
    {{- toYaml .Values.kvcache_config | nindent 4 }} 